Resunet/ViewModels/PaginationViewModel.cs
namespace Estore.ViewModels
{
    public class PaginationViewModel
    {
        public int Page { get; set; } = 1;
        public int TotalPages { get; set; } = 1;
        public int TotalCount { get; set; } = 0;
        public int PageSize { get; set; } = 24;
        public string BaseUrl { get; set; } = null!;
    }
}

Resunet/ViewComponents/MainMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Estore.BL.Auth;

namespace Estore.ViewComponents
{
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly ICurrentUser _currentUser;

        public MainMenuViewComponent(ICurrentUser currentUser)
        {
            _currentUser = currentUser;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            bool isLoggedIn = await _currentUser.IsLoggedInAsync();
            return View("Index", isLoggedIn);
        }
    }
}

Resunet/Views/Shared/_Breadcrumps.cshtml
@model List<BreadcrumpModel>

<div class="breadcrump">
    @for (int i = 0; i < Model.Count; i++)
    {
        if (i > 0)
        {
            <text> / </text>
        }
        <a href="@Model[i].Link">@Model[i].Name</a>
    }
</div>

Resunet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Магазин БХВ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Estore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-light navbar-expand-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/data//Logo_BHV_2023.png" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Новости</a>
                        </li>
                        @await Component.InvokeAsync("MainMenu")
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-3">
                    <h4>Издательство</h4>
                    <ul>
                        <li><a href="/about">О нас</a></li>
                        <li><a href="/news">Новости</a></li>
                    </ul>
                    <ul>
                        <li><a href="/priglashaem-avtorov">Приглашаем авторов</a></li>
                        <li><a href="/reclama">Для рекламодателей</a></li>
                        <li><a href="/vacancii">Вакансии</a></li>
                        <li><a href="/contact-us">Контакты</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-lg-3">
                    <h4>Магазин</h4>

                    <ul>
                        <li><a href="/faq">Вопросы и ответы</a></li>
                        <li><a href="/dostavka">Оплата и доставка</a></li>
                        <li><a href="/gde-kupit">Где купить</a></li>
                        <li><a href="/prajs-listy">Прайс лист</a></li>
                        <li><a href="/rekvizity">Реквизиты</a></li>
                    </ul>

                    <ul>
                        <li><a href="/sovmestnye-pokupki">Совместные покупки</a></li>
                    </ul>

                    <ul>
                        <li><a href="/soglashenie-o-prodazhe-tovarov">Соглашение о продаже</a></li>
                        <li><a href="/politika-konfidentsialnosti">Политика конфиденциальности</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-lg-3">
                    <h4>Присоединяйтесь</h4>
                    <a href="https://vk.com/club642726">
                        <img alt="Детская редакция БХВ" width="104" height="32" 
                            role="img"
                            data-src="https://bhv.ru/wp-content/uploads/2020/02/vk_deti.svg" 
                            class="alignleft wp-image-86261 lazyloaded" 
                            src="https://bhv.ru/wp-content/uploads/2020/02/vk_deti.svg" />
                        <noscript>
                        <img class="alignleft wp-image-86261" role="img"
                             src="https://bhv.ru/wp-content/uploads/2020/02/vk_deti.svg" alt="Детская редакция БХВ"
                             width="104" height="32" />
                        </noscript>
                    </a>
                    <a href="http://vk.com/bhvspb">
                        <img role="img" alt="Компьютерная редакция БХВ" width="129" height="32" data-src="https://bhv.ru/wp-content/uploads/2020/02/vk_PC.svg" class="alignleft wp-image-86257 lazyloaded" src="https://bhv.ru/wp-content/uploads/2020/02/vk_PC.svg"><noscript>
                            <img class="alignleft wp-image-86257" role="img"
                                 src="https://bhv.ru/wp-content/uploads/2020/02/vk_PC.svg" alt="Компьютерная редакция БХВ" width="129" height="32" />
                        </noscript>
                    </a>
                    <hr />

                    <ul>
                        <li><a href="/login">Войти</a></li>
                        <li><a href="/register">Регистрация</a></li>
                        <li><a href="/my-account/">Мой аккаунт</a></li>
                        <li><a href="/my-account/orders">Счета</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-lg-3">
                    <h4>Оплата и доставка</h4>
                    <a href="https://bhv.ru/oplata/">
                        <img role="img" alt="" style="width:100%;max-width:300px;max-height:300px" 
                            data-src="https://bhv.ru/wp-content/uploads/2019/10/Oplata_new.svg" 
                            class="alignnone size-medium wp-image-73321 ls-is-cached lazyloaded" 
                            src="https://bhv.ru/wp-content/uploads/2019/10/Oplata_new.svg">
                        <noscript>
                            <img class="alignnone size-medium wp-image-73321" role="img" src="https://bhv.ru/wp-content/uploads/2019/10/Oplata_new.svg" alt="" width="300" height="300" />
                        </noscript>
                    </a>
                    <a href="https://bhv.ru/dostavka/">
                        <img alt="" style="width:100%;max-width:300px" 
                            data-src="https://bhv.ru/wp-content/uploads/2020/03/my-sdek.svg" 
                            class="alignnone size-medium wp-image-16393 ls-is-cached lazyloaded" 
                            src="https://bhv.ru/wp-content/uploads/2020/03/my-sdek.svg">
                    <noscript>
                        <img class="alignnone size-medium wp-image-16393" src="https://bhv.ru/wp-content/uploads/2020/03/my-sdek.svg" alt="" width="300" height="113" />
                    </noscript></a>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    &copy; 2023 - БХВ
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Resunet/Views/Shared/_Pagination.cshtml
@model PaginationViewModel

<div class="navigation row">
    <div class="col-md-4">
        Найдено @Model.TotalCount
    </div>
    <div class="col-md-4 offset-4 pages">
        @for (int index = 1; index <= Model.TotalPages; index++)
        {
            if (index == Model.Page)
            {
                <span class="current-page">@index</span>
            }
            else
            { 
                <a href="@Model.BaseUrl?page=@index">@index</a>
            }
        }
    </div>
</div>

Resunet/Views/Shared/_ProductCard.cshtml
@model ProductCardModel

<div class="col-lg-2 col-sm-4 col-6">
    <div class="card book-card">
        <a href="/product/@Model.UniqueId">
            <img class="card-img-top" src="@Model.ProductImage" alt="@Model.ProductName"/>
        </a>
        <div class="card-body">
            <a href="/product/@Model.UniqueId">
                <div class="card-title">
                    @Model.ProductName
                </div>
            </a>
            <div class="current-price">@Model.Price руб.</div>
        </div>
    </div>
</div>